# Travis-CI build file for VMime
# See http://travis-ci.org for details

language: cpp

compiler:
  - gcc
  - clang

# Settings
env:
  - OPTIONS="-DVMIME_SENDMAIL_PATH=/path/to/sendmail -DCMAKE_BUILD_TYPE=Debug"

# Make sure some required tools/libraries are installed
install:
  - sudo apt-get update >/dev/null
  - sudo apt-get -q install cmake valgrind
  - sudo apt-get -q install libgsasl7-dev libgnutls-dev libssl-dev

# Run the build script
script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install $OPTIONS
  - cmake --build . --target install
