# Travis-CI build file for VMime
# See http://travis-ci.org for details

language: cpp

compiler:
  - gcc
  - clang

# Settings
env:
  - CTEST_OUTPUT_ON_FAILURE=1 OPTIONS="-DVMIME_SENDMAIL_PATH=/path/to/sendmail -DCMAKE_BUILD_TYPE=Debug -DVMIME_BUILD_TESTS=ON"
  - CTEST_OUTPUT_ON_FAILURE=1 OPTIONS="-DVMIME_SENDMAIL_PATH=/path/to/sendmail -DCMAKE_BUILD_TYPE=Debug -DVMIME_BUILD_TESTS=ON -DVMIME_CHARSETCONV_LIB_IS_ICONV=OFF -DVMIME_CHARSETCONV_LIB_IS_ICU=ON"
  - CTEST_OUTPUT_ON_FAILURE=1 OPTIONS="-DVMIME_SENDMAIL_PATH=/path/to/sendmail -DCMAKE_BUILD_TYPE=Debug -DVMIME_BUILD_TESTS=ON -DVMIME_TLS_SUPPORT_LIB_IS_GNUTLS=OFF -DVMIME_TLS_SUPPORT_LIB_IS_OPENSSL=ON"

# Make sure some required tools/libraries are installed
install:
  - sudo apt-get update >/dev/null
  - sudo apt-get -q install cmake libcppunit-dev valgrind
  - sudo apt-get -q install libgsasl7-dev libgnutls-dev libssl-dev libicu-dev

# Run the build script
script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install $OPTIONS
  - cmake .. -L
  - echo "============================== config.hpp =============================="
  - cat ../vmime/config.hpp
  - echo "========================== export-shared.hpp ==========================="
  - cat ../vmime/export-shared.hpp
  - echo "========================== export-static.hpp ==========================="
  - cat ../vmime/export-static.hpp
  - echo "================================ BUILD ================================="
  - cmake --build . --target install
  - ctest
